require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-permissions/scripts/setup'

platform :ios, '16.0'
prepare_react_native_project!

use_frameworks! :linkage => :static

# Setup permissions
setup_permissions([
  'Camera',
  'PhotoLibrary',
  'MediaLibrary',
  'Notifications'
])

target 'pe2pia' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false, # Fabric should be disabled too if you're disabling the new arch
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :new_arch_enabled => false
  )


  # Firebase dependencies
  pod 'Firebase', '11.8.0'
  pod 'FirebaseCore', '11.8.0', :modular_headers => true
  pod 'FirebaseAuth', '11.8.0'
  pod 'FirebaseFirestore', '11.8.0'
  pod 'FirebaseMessaging', '11.8.0'
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCoreInternal', '11.8.0', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseFirestoreInternal', :modular_headers => true
  pod 'RecaptchaInterop', :modular_headers => true

  # gRPC dependencies
  pod 'gRPC-Core', :modular_headers => true
  pod 'gRPC-C++', :modular_headers => true
  pod 'abseil', :modular_headers => true
  pod 'BoringSSL-GRPC', :modular_headers => true

  # Other dependencies
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'TweetNacl', '1.0.2'

  target 'pe2piaTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
        config.build_settings['DEFINES_MODULE'] = 'YES'
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
  end
end
